fix(): set AUTH_AUDIENCE variable
Fix error in dasboard pod logs for missing variable
"AUTH_AUDIENCE or AUTH0_AUDIENCE environment variable must be set"
on the login page "There was an error logging you in.
Error: Unauthenticated"